# Generated by Django 5.2.3 on 2025-06-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_profile_bio_remove_profile_phone_profile_dob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedplace",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedplace",
            name="lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
