# Generated by Django 5.2.3 on 2025-06-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_visitedplace_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewed_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
