# Generated by Django 5.2.3 on 2025-06-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_review_rating_alter_review_reviewed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
