# Generated by Django 5.2.3 on 2025-06-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_review_rating_alter_review_reviewed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedplace",
            name="amenity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="visitedplace",
            name="amenity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
