# Generated by Django 5.2.3 on 2025-06-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitedplace",
            name="amenity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
