# Generated by Django 5.2.3 on 2025-06-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_visitedplace_amenity"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedplace",
            name="amenity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
